version: '3.8'

services:
  app:
    build: .
    container_name: user-profile-app
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
  
volumes:
  redis-data:

networks:
  app-network: